Feature sum
michaeljclausen/xcell pull request #1
Opened 2017-05-01 01:58 UTC by michaeljclausen

Here it is!

2017-05-01 20:28 UTC, speschellk requested changes

2017-05-01 20:28 UTC, speschellk commented on client/js/table-model.js
> +    for (let row = 0; row < numRows - 1; row +=1) {
It's unconventional to have for loops in a class constructor. Is there a different way you can achieve the same functionality?

2017-05-01 20:28 UTC, speschellk commented on client/js/table-view.js
> +    for(let i = 0; i < this.model.numRows - 1; i += 1) {
Replace all += 1 instances with "++" (increments by one). Likewise, a -= 1 can be replaced with "--" (decrements by 1).

2017-05-01 20:28 UTC, speschellk commented on client/js/test/table-view.test.js
> +    it('should add a row', () => {
What should? When? Make your test assertions descriptive of the functionality. A better one would be "if adds a row when the Add Row button is clicked", for example.

2017-05-02 18:29 UTC, michaeljclausen commented on client/js/table-view.js
> +    for(let i = 0; i < this.model.numRows - 1; i += 1) {
Ok... but I was just going by what Doug Crockford said to do ;)

2017-05-02 22:51 UTC, speschellk approved these changes

2017-05-02 22:51 UTC, merged